### ISSUE TITLE
transform-runtime err

### ISSUE THREAD

**Issue by winkler1** [juliantrueflynn/slack_clone#1]
```❯ npm install

> slack_clone@1.0.0 postinstall /Users/jeffwinkler/repos/tmp/slack_clone
> webpack

Hash: acff6a65007aa26d7ed6
Version: webpack 4.20.2
Time: 1401ms
Built at: 2019-03-25 11:46:03
 2 assets
Entrypoint main = bundle.js bundle.js.map
[0] ./frontend/SlackClone.jsx 1.48 KiB {0} [built] [failed] [1 error]

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in ./frontend/SlackClone.jsx
Module build failed (from ./node_modules/babel-loader/lib/index.js):
ReferenceError: Unknown plugin "transform-runtime" specified in "/Users/jeffwinkler/repos/tmp/.babelrc" at 0, attempted to resolve relative to "/Users/jeffwinkler/repos/tmp"
```

Tried adding the plugin via `npm install --save-dev babel-plugin-transform-runtime`

and babel-runtime as a production dependency (with --save).

`npm install --save babel-runtime`

but has not fixed it, any ideas?

**Comment by juliantrueflynn** [comment]
I will check this out today or by latest tomorrow and see what the issue is. That babel plugin is used so Redux Saga can work.

**Comment by juliantrueflynn** [comment]
@winkler1 I played around with this for a bit and I'm fairly sure this is because your `.babelrc` file is causing interference. I have no `.babelrc` file for my project, but create one to make cloning this project easier.

I know from our chat earlier you probably don't need this project as a reference anymore now that you have something working. If you want to check your `.babelrc` configuration and you become positive it's not the cause then feel free to comment and I can re-open ticket.
